import os

cpppath = ['.']
libpath = []
libs    = []

preciceRootPath = os.getenv('PRECICE_ROOT')
cpppath.append(preciceRootPath + '/src/precice/bindings/c')

# Libs
libpath.append(preciceRootPath + '/build/last/')
libs.append('precice')

fortranCompiler = 'gfortran'

envCompile = Environment ( 
   CPPPATH    = cpppath,
   LIBPATH    = libpath,
   LIBS       = libs,
   ENV        = os.environ  # propagates environment variables to scons  
   )

  
envCompile.Object ('solverdummy.c')

envLink = envCompile.Clone (CC='g++')
envLink.Program('solverdummy.o')
