#ifndef PRECICE_AABSTRACTIMPLEMENTATION_H_
#define PRECICE_AABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "precice/InitializerNativeDispatcher.h"

#include "precice/Main.h"
#include "precice/Initializer.h"

#include "Component.h"
namespace precice { 

     class AAbstractImplementation;
}



class precice::AAbstractImplementation: public Component ,public precice::Main,public precice::Initializer{
     protected:
       precice::InitializerNativeDispatcher* _b;
   
     public:
       AAbstractImplementation();
       virtual ~AAbstractImplementation();
       /**
        * @see Case class 
        */
       void connectb(precice::InitializerNativeDispatcher* port);
       void disconnectb();
 
		void initializeVertexesParallel(const int* vertexes, const int vertexes_len);
		void initializeAddressesParallel(const std::string* addresses, const int addresses_len);
		void mainParallel();
};     


#endif
