#ifndef PRECICE_BABSTRACTIMPLEMENTATION_H_
#define PRECICE_BABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "precice/InitializerNativeDispatcher.h"

#include "precice/Main.h"
#include "precice/Initializer.h"
#include "precice/Communicator.h"

#include "Component.h"
namespace precice { 

     class BAbstractImplementation;
}



class precice::BAbstractImplementation: public Component ,public precice::Main,public precice::Initializer,public precice::Communicator{
     protected:
       precice::InitializerNativeDispatcher* _a;
   
     public:
       BAbstractImplementation();
       virtual ~BAbstractImplementation();
       /**
        * @see Case class 
        */
       void connecta(precice::InitializerNativeDispatcher* port);
       void disconnecta();
 
		void setDataParallel(const double* data, const int data_len);
		void initializeVertexesParallel(const int* vertexes, const int vertexes_len);
		void initializeAddressesParallel(const std::string* addresses, const int addresses_len);
		void mainParallel();
};     


#endif
