#ifndef PRECICE_COMMUNICATOR_H_
#define PRECICE_COMMUNICATOR_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace precice { 

     class Communicator;
}

class precice::Communicator {
  public:
    virtual ~Communicator(){}
     virtual void setData(const double data,const int index,const int rank,int& tag)=0;
     virtual void setDataParallel(const double data,const int index,const int rank,int& tag)=0;


};

#endif
