#ifndef PRECICE_INITIALIZER2NATIVE2JAVAPLAINPORT_H_
#define PRECICE_INITIALIZER2NATIVE2JAVAPLAINPORT_H_ 

#include "precice/Initializer.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_precice_InitializerNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_precice_InitializerNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace precice { 

     class InitializerNative2JavaPlainPort;
}

class precice::InitializerNative2JavaPlainPort: public precice::Initializer{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    InitializerNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~InitializerNative2JavaPlainPort();
    void acknowledge(const int identifier,int& tag);  
    void acknowledgeParallel(const int identifier,int& tag);
   
    void initialize(const std::string* addresses, const int addresses_len,const int* vertexes, const int vertexes_len);  
    void initializeParallel(const std::string* addresses, const int addresses_len,const int* vertexes, const int vertexes_len);
   
};
#endif
