#ifndef PRECICE_MAIN_H_
#define PRECICE_MAIN_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace precice { 

     class Main;
}

class precice::Main {
  public:
    virtual ~Main(){}
     virtual void main()=0;
     virtual void mainParallel()=0;


};

#endif
