#ifndef PRECICE_RECEIVER2NATIVE2JAVAPLAINPORT_H_
#define PRECICE_RECEIVER2NATIVE2JAVAPLAINPORT_H_ 

#include "precice/Receiver.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_precice_ReceiverNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_precice_ReceiverNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace precice { 

     class ReceiverNative2JavaPlainPort;
}

class precice::ReceiverNative2JavaPlainPort: public precice::Receiver{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    ReceiverNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~ReceiverNative2JavaPlainPort();
    void receive(const double data,const int index,const int rank,int& tag);  
    void receiveParallel(const double data,const int index,const int rank,int& tag);
   
};
#endif
