todisp('Compiling cpp functions...');
mex ~/precice/src/precice/bindings/matlab/+precice/@SolverInterface/private/preciceGateway.cpp -output ...
    ~/precice/src/precice/bindings/matlab/+precice/@SolverInterface/private/preciceGateway -lprecice;
mex ~/precice/src/precice/bindings/matlab/+precice/@Constants/private/preciceConstants.cpp -output ...
    ~/precice/src/precice/bindings/matlab/+precice/@Constants/private/preciceConstants -lprecice;