FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq update && apt-get -qq install wget software-properties-common git build-essential pkg-config sudo

# Install preCICE v2.2.1 from the Debian package
RUN wget https://github.com/precice/precice/releases/download/v2.2.1/libprecice2_2.2.1_focal.deb && \
    apt install -y ./libprecice2_2.2.1_focal.deb

# Create user precice
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} precice \
    && useradd -u ${uid} -g ${gid} -m -s /bin/bash precice \
    && sudo usermod -a -G sudo precice

# Setup passwordless sudo
RUN echo "ALL            ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers

# Switch to the user precice
USER precice
WORKDIR /home/precice
ENV USER=precice

# Use bash instead of default sh
SHELL ["/bin/bash", "-c"]
