# CMake generated Testfile for
# Source directory: /home/nille/precice-develop/precice/tools/profiling
# Build directory: /home/nille/precice-develop/precice/tools/profiling
#
# This file includes the relevant testing commands required for
# testing this directory and lists subdirectories to be tested as well.
add_test(precice.tools.profiling.from-common-dir "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/from-common-dir" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/from-common-dir" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.from-common-dir PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.from-common-dir" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.one-parallel-solver "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/one-parallel-solver" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/one-parallel-solver" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.one-parallel-solver PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.one-parallel-solver" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.one-parallel-solver-different-ids "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/one-parallel-solver-different-ids" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/one-parallel-solver-different-ids" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.one-parallel-solver-different-ids PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.one-parallel-solver-different-ids" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.one-serial-damaged "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/one-serial-damaged" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/one-serial-damaged" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.one-serial-damaged PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.one-serial-damaged" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.one-serial-solver "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/one-serial-solver" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/one-serial-solver" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.one-serial-solver PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.one-serial-solver" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.one-solver-multiple-runs "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/one-solver-multiple-runs" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/one-solver-multiple-runs" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.one-solver-multiple-runs PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.one-solver-multiple-runs" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.two-mixed-solvers "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/two-mixed-solvers" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/two-mixed-solvers" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.two-mixed-solvers PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.two-mixed-solvers" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.two-parallel-solvers "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/two-parallel-solvers" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/two-parallel-solvers" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.two-parallel-solvers PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.two-parallel-solvers" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.two-serial-solvers "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/two-serial-solvers" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/two-serial-solvers" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.two-serial-solvers PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.two-serial-solvers" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;37;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
add_test(precice.tools.profiling.from-solver-dirs "/usr/bin/cmake" "-DPROFILING_SCRIPT=/home/nille/precice-develop/precice/tools/profiling/precice-profiling" "-DTEST_FOLDER=/home/nille/precice-develop/precice/tools/profiling/tests/from-solver-dirs" "-DFOLDER_ARG=/home/nille/precice-develop/precice/tools/profiling/tests/from-solver-dirs/A;/home/nille/precice-develop/precice/tools/profiling/tests/from-solver-dirs/B" "-P" "/home/nille/precice-develop/precice/tools/profiling/tests/simple-test.cmake")
set_tests_properties(precice.tools.profiling.from-solver-dirs PROPERTIES  WORKING_DIRECTORY "/home/nille/precice-develop/precice/TestOutput/tools.profiling.from-solver-dirs" _BACKTRACE_TRIPLES "/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;51;add_test;/home/nille/precice-develop/precice/tools/profiling/CMakeLists.txt;0;")
