# structure/SConstruct
#
# SCons buildfile for "Structure0815" solver
#
######################################

import os;
import sys;
  
##### Declare build variables and default values
#
cppdefines = []   
libpath = [ 
   '../../build/release-nompi-nosockets-nospirit2-nopython/' # Path to preCICE library
   #'../../build/release/'
   ]      
libs = [ 
   'precice'  # preCICE library 
   #'python2.6', # Python library (shared)
   #'pthread' 
   ]
cpppath = []   
ccflags = []   
cxx = 'g++'      # For systems offering mpicxx compiler


#ccflags.append('-g3')
ccflags.append('-O3')

#libpath.append (preciceRoot + '/build/' + buildmode + '-dim2-nompi/')


##### Setup build environment and issue builds
#
env = Environment ( 
   CPPDEFINES = cppdefines,  # defines for preprocessor (#define xyz)
   LIBPATH    = libpath,     # path to libraries used
   LIBS       = libs,        # libraries used (without prefix "lib" and suffix ".a"/".so"/...)
   CPPPATH    = cpppath,     # pathes where the preprocessor should look for files
   CCFLAGS    = ccflags,     # flags for the c/c++ compilers
   CXX        = cxx,         # the c++ compiler that should be used
   ENV        = os.environ  # propagates environment variables to scons  
   )
   
env.Program ( 'solverdummy', Glob('*.cpp') )