# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget precice::precice precice::precice-tools)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target precice::precice
add_library(precice::precice SHARED IMPORTED)

set_target_properties(precice::precice PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/elia/university/preCICE_new/precice/src;/home/elia/university/preCICE_new/precice/_clang-tidy/src"
)

# Create imported target precice::precice-tools
add_executable(precice::precice-tools IMPORTED)

# Import target "precice::precice" for configuration "Debug"
set_property(TARGET precice::precice APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(precice::precice PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "Python3::Python"
  IMPORTED_LOCATION_DEBUG "/home/elia/university/preCICE_new/precice/_clang-tidy/libprecice.so.2.4.0"
  IMPORTED_SONAME_DEBUG "libprecice.so.2"
  )

# Import target "precice::precice-tools" for configuration "Debug"
set_property(TARGET precice::precice-tools APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(precice::precice-tools PROPERTIES
  IMPORTED_LOCATION_DEBUG "/home/elia/university/preCICE_new/precice/_clang-tidy/precice-tools"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
