//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSICommDispatcher implements FSIComm {

  protected java.util.Set<FSIComm>  _destinations;
  
  public FSICommDispatcher() {
    _destinations = java.util.Collections.synchronizedSet(new java.util.HashSet<FSIComm>());
  }
  
  public long getReference(){
    return 0;
  }
  
  
  public void setReference(long ref){
  }
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(FSIComm  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "connect(...)", "port already was connected", null );
    }
    _destinations.add(port);
  }
    
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(FSIComm  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port that was not connected before", null );
    }
     
    if (!_destinations.contains(port)) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port from port that was not connected before", null );
    }
    _destinations.remove(port);
  }
  
  public boolean isConnected(){
     return !_destinations.isEmpty();
  }
  
  public void transferCoordinates(final int coordId[],final int offsets[],final String hosts[]) {
    for(FSIComm port: _destinations)
      port.transferCoordinates(coordId,offsets,hosts);
  }
  
  public void transferCoordinatesParallel(final int coordId[],final int offsets[],final String hosts[]) {
    for(FSIComm port: _destinations)
      port.transferCoordinatesParallel(coordId,offsets,hosts);
  }
  
  public void transferCoordinatesForIntegerEnums(final int coordId[],final int offsets[],final String hosts[]) {
    for(FSIComm port: _destinations){
      
      port.transferCoordinates(coordId,offsets,hosts);
      
    }
  }
  public void transferData(final double data[]) {
    for(FSIComm port: _destinations)
      port.transferData(data);
  }
  
  public void transferDataParallel(final double data[]) {
    for(FSIComm port: _destinations)
      port.transferDataParallel(data);
  }
  
  public void transferDataForIntegerEnums(final double data[]) {
    for(FSIComm port: _destinations){
      
      port.transferData(data);
      
    }
  }
  
//  public void lock() {
//    if (_destination!=null) {
//      _destination.lock();
//    }
//  }
 
//  public void unlock() {
//    if (_destination!=null) {
//      _destination.unlock();
//    }
//  }
  
}
 


