//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSICommPlainJavaPort extends FSICommAbstractPort {

  public FSICommPlainJavaPort() {
    super();
  }
  

  public void transferCoordinates(final int coordId[],final int offsets[],final String hosts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferCoordinates(coordId,offsets,hosts);
      //_destination.unlock();
    //}
  }
  
  public void transferCoordinatesParallel(final int coordId[],final int offsets[],final String hosts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferCoordinatesParallel(coordId,offsets,hosts);
      //_destination.unlock();
    //}
  }
  
  
  

  public void startDataTransfer() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.startDataTransfer();
      //_destination.unlock();
    //}
  }
  
  public void startDataTransferParallel() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.startDataTransferParallel();
      //_destination.unlock();
    //}
  }
  
  
  

  public void endDataTransfer(int ack[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.endDataTransfer(ack);
      //_destination.unlock();
    //}
  }
  
  public void endDataTransferParallel(int ack[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.endDataTransferParallel(ack);
      //_destination.unlock();
    //}
  }
  
  
  
  

}
 


