//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public interface FSIComm  {
  class IntegerWrapper {
    public int value;
  }
  class DoubleWrapper {
    public double value;
  }
  class StringWrapper {
    public String value;
  }
  class BooleanWrapper {
    public boolean value;
  }
  public long getReference();
  public void setReference(long ref);
  //void lock();
 
  //void unlock();
  

  public void transferCoordinates(final int coordId[],final int offsets[],final String hosts[]);
  public void transferCoordinatesParallel(final int coordId[],final int offsets[],final String hosts[]);

  public void startDataTransfer();
  public void startDataTransferParallel();

  public void endDataTransfer(int ack[]);
  public void endDataTransferParallel(int ack[]);


}
 


