//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSICommPlainJavaPort extends FSICommAbstractPort {

  public FSICommPlainJavaPort() {
    super();
  }
  

  public void transferCoordinates(final int coordId[],final int offsets[],final String hosts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferCoordinates(coordId,offsets,hosts);
      //_destination.unlock();
    //}
  }
  
  public void transferCoordinatesParallel(final int coordId[],final int offsets[],final String hosts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferCoordinatesParallel(coordId,offsets,hosts);
      //_destination.unlock();
    //}
  }
  
  
  

  public void transferData(final double data[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferData(data);
      //_destination.unlock();
    //}
  }
  
  public void transferDataParallel(final double data[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferDataParallel(data);
      //_destination.unlock();
    //}
  }
  
  
  
  

}
 


