//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSIDataPlainJavaPort extends FSIDataAbstractPort {

  public FSIDataPlainJavaPort() {
    super();
  }
  

  public void transferData(final int coordId[],final double data[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferData(coordId,data);
      //_destination.unlock();
    //}
  }
  
  public void transferDataParallel(final int coordId[],final double data[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.transferDataParallel(coordId,data);
      //_destination.unlock();
    //}
  }
  
  
  

  public void dataAck(int ack[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.dataAck(ack);
      //_destination.unlock();
    //}
  }
  
  public void dataAckParallel(int ack[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.dataAckParallel(ack);
      //_destination.unlock();
    //}
  }
  
  
  
  

}
 


