//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSIDataDispatcher implements FSIData {

  protected java.util.Set<FSIData>  _destinations;
  
  public FSIDataDispatcher() {
    _destinations = java.util.Collections.synchronizedSet(new java.util.HashSet<FSIData>());
  }
  
  public long getReference(){
    return 0;
  }
  
  
  public void setReference(long ref){
  }
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(FSIData  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "connect(...)", "port already was connected", null );
    }
    _destinations.add(port);
  }
    
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(FSIData  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port that was not connected before", null );
    }
     
    if (!_destinations.contains(port)) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port from port that was not connected before", null );
    }
    _destinations.remove(port);
  }
  
  public boolean isConnected(){
     return !_destinations.isEmpty();
  }
  
  public void transferData(final int coordId[],final double data[]) {
    for(FSIData port: _destinations)
      port.transferData(coordId,data);
  }
  
  public void transferDataParallel(final int coordId[],final double data[]) {
    for(FSIData port: _destinations)
      port.transferDataParallel(coordId,data);
  }
  
  public void transferDataForIntegerEnums(final int coordId[],final double data[]) {
    for(FSIData port: _destinations){
      
      port.transferData(coordId,data);
      
    }
  }
  public void dataAck(int ack[]) {
    for(FSIData port: _destinations)
      port.dataAck(ack);
  }
  
  public void dataAckParallel(int ack[]) {
    for(FSIData port: _destinations)
      port.dataAckParallel(ack);
  }
  
  public void dataAckForIntegerEnums(int ack[]) {
    for(FSIData port: _destinations){
      
      port.dataAck(ack);
      
    }
  }
  
//  public void lock() {
//    if (_destination!=null) {
//      _destination.lock();
//    }
//  }
 
//  public void unlock() {
//    if (_destination!=null) {
//      _destination.unlock();
//    }
//  }
  
}
 


