//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSIDataSocket2JavaPlainPort extends FSIDataAbstractSocketPort 
     implements java.lang.Runnable,java.nio.channels.CompletionHandler< java.nio.channels.AsynchronousSocketChannel, Object>{

  interface FSIDataSocketInvoker {
    void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException;
  } 
  private long _ref;
  private FSIDataSocketInvoker[] _invokers;
  private java.util.concurrent.ExecutorService _executor;
  public FSIDataSocket2JavaPlainPort(String host,int port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(host,port);
    _invokers = new  FSIDataSocketInvoker[216];
    	_invokers[14]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_transferData();
		}
	};
	_invokers[15]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_transferDataParallel();
		}
	};
	_invokers[16]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_dataAck();
		}
	};
	_invokers[17]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_dataAckParallel();
		}
	};

  }
  
  public FSIDataSocket2JavaPlainPort() throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super();
    _invokers = new  FSIDataSocketInvoker[216];
    	_invokers[14]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_transferData();
		}
	};
	_invokers[15]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_transferDataParallel();
		}
	};
	_invokers[16]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_dataAck();
		}
	};
	_invokers[17]= new FSIDataSocketInvoker(){
		public void invoke() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
			invoke_dataAckParallel();
		}
	};

  }
  
  @Override
  public void completed(java.nio.channels.AsynchronousSocketChannel result, java.lang.Object attachment) {
    super.completed(result,attachment);
    //createInstance();
    _executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    _executor.execute(this);           
   
  }

  @Override
  public void failed(java.lang.Throwable exc, java.lang.Object attachment) {
     // TODO Auto-generated method stub
     
  }
  
  public void createInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=0;
     sendIntData(methodId);
     _ref=readLongData();
    
  }
  public void destroyInstance() throws de.tum.ascodt.utils.exceptions.ASCoDTException{
     int methodId=1;
     sendIntData(methodId);
     sendLongData(_ref);
          
  }
  
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  //public void disconnect(FSIData  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     //destroyInstance();
  //   super.disconnect(port);
  //}
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }
  
  public void close(){
     if(_executor!=null&&!_executor.isShutdown())
          _executor.shutdownNow();
     super.close();
  }
  public void run(){
     int methodId=0;
     try{
          methodId=readIntData(); 
          while(methodId!=-1){
             
              _invokers[methodId].invoke();
              methodId=readIntData();      
          }
         
     }catch(Exception e){
          de.tum.ascodt.plugin.utils.exceptions.ErrorWriterDevice.getInstance().println(e);
     }
     super.close();
  }

  public void invoke_dataAck() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int [] ack= new int[1];
readIntData(ack,1);

     dataAck(ack);
     sendIntData(ack);

  }
  public void invoke_dataAckParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void dataAck(int ack[]) {
     _destination.dataAck(ack);
  }
  public void dataAckParallel(int ack[]) {
     _destination.dataAckParallel(ack);
  }
  
  

  public void invoke_transferData() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
     int coordId_len=readIntData();
int []coordId=new int[coordId_len];
readIntData(coordId,coordId_len);
int data_len=readIntData();
double []data=new double[data_len];
readDoubleData(data,data_len);

     transferData(coordId,data);
     
  }
  public void invoke_transferDataParallel() throws 
         de.tum.ascodt.utils.exceptions.ASCoDTException{
    
  }
  public void transferData(final int coordId[],final double data[]) {
     _destination.transferData(coordId,data);
  }
  public void transferDataParallel(final int coordId[],final double data[]) {
     _destination.transferDataParallel(coordId,data);
  }
  
  


}
 


