//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public interface FSIDummyB extends fsi.FSIComm,de.tum.ascodt.repository.entities.CxxReverseRemoteSocketComponent {

  public static final String Implementation = "";
  

}
 


