//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSITestPlainJavaPort extends FSITestAbstractPort {

  public FSITestPlainJavaPort() {
    super();
  }
  

  public void test() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.test();
      //_destination.unlock();
    //}
  }
  
  public void testParallel() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.testParallel();
      //_destination.unlock();
    //}
  }
  
  
  
  

}
 


