//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSITestNative2JavaPlainPort extends FSITestAbstractPort {

  private long _ref;
  public FSITestNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(FSITest  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     super.disconnect(port);
  }
  
  public void destroy(){
     destroyInstance(_ref);    
  }
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void test() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.test();
      //_destination.unlock();
    //}
  }
  
  public void testParallel() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.testParallel();
      //_destination.unlock();
    //}
  }
  
  
  


}
 


