//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSITestNativeDispatcher extends FSITestDispatcher {
  protected long _ref;
  
  public FSITestNativeDispatcher(){
    createInstance();
  }
  
  public native void createInstance(); 
  
  public void destroy(){
    destroyInstance(_ref);
  }
  
  public native void destroyInstance(long ref);
  public long getReference(){
    return _ref;
  }
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(FSITest  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,port.getReference());
  }
  
  public native void connect(long ref, long portRef);
  
  public void disconnect(FSITest  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.disconnect(port);
    disconnect(_ref,port.getReference());
  }
  
  public native void disconnect(long ref, long portRef);

}
