(if (not (rp-var-object 'udf/amplitude))
   (rp-var-define 'udf/amplitude 1.0 'float #f)
)
(if (not (rp-var-object 'udf/period))
   (rp-var-define 'udf/period 1.0 'float #f)
)
(if (not (rp-var-object 'udf/surfacelevel))
   (rp-var-define 'udf/surfacelevel 1.0 'float #f)
)
(if (not (rp-var-object 'udf/flipzones))
   (rp-var-define 'udf/flipzones 0 'int #f)
)
(if (not (rp-var-object 'udf/waveheight))
   (rp-var-define 'udf/waveheight 0.0 'float #f)
)
(if (not (rp-var-object 'udf/wavelength))
   (rp-var-define 'udf/wavelength 0.0 'float #f)
)
(rpsetvar 'udf/amplitude    0.075758)
(rpsetvar 'udf/period       1.5)
(rpsetvar 'udf/surfacelevel 0.5)
(rpsetvar 'udf/flipzones    0)
(rpsetvar 'udf/waveheight   0.14)
(rpsetvar 'udf/wavelength   2.8)
