(if (not (rp-var-object 'udf/convergence))
   (rp-var-define 'udf/convergence 1 'int #f)
)
(if (not (rp-var-object 'udf/ongoing))
   (rp-var-define 'udf/ongoing 1 'int #f)
)
(if (not (rp-var-object 'udf/subcycling))
   (rp-var-define 'udf/subcycling 1 'int #f)
)
(if (not (rp-var-object 'udf/iterate))
   (rp-var-define 'udf/iterate 0 'int #f)
)

(rpsetvar 'dynamesh/update-in-timestep/residual-criterion -1.0)
(init-flow)
