(if (not (rp-var-object 'udf/convergence))
   (rp-var-define 'udf/convergence 1 'int #f)
)
(if (not (rp-var-object 'udf/ongoing))
   (rp-var-define 'udf/ongoing 1 'int #f)
)
(if (not (rp-var-object 'udf/iterate))
   (rp-var-define 'udf/iterate 0 'int #f)
)
(if (not (rp-var-object 'udf/checkpoint))
   (rp-var-define 'udf/checkpoint 0 'int #f)
)

(rpsetvar 'udf/convergence 1)
(rpsetvar 'udf/ongoing 1)
(rpsetvar 'udf/iterate 0)
(rpsetvar 'udf/checkpoint 0)
(rpsetvar 'dynamesh/update-in-timestep/residual-criterion -1.0)
(init-flow)
