#ifndef FSI_FSICOMM_H_
#define FSI_FSICOMM_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace fsi { 

     class FSIComm;
}

class fsi::FSIComm {
  public:
    virtual ~FSIComm(){}
     virtual void transferData(const double* data, const int data_len)=0;
     virtual void transferDataParallel(const double* data, const int data_len)=0;
     virtual void transferCoordinates(const double* coord, const int coord_len)=0;
     virtual void transferCoordinatesParallel(const double* coord, const int coord_len)=0;


};

#endif
