#ifndef FSI_FSICOMM2NATIVE2JAVAPLAINPORT_H_
#define FSI_FSICOMM2NATIVE2JAVAPLAINPORT_H_ 

#include "fsi/FSIComm.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_fsi_FSICommNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_fsi_FSICommNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace fsi { 

     class FSICommNative2JavaPlainPort;
}

class fsi::FSICommNative2JavaPlainPort: public fsi::FSIComm{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    FSICommNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~FSICommNative2JavaPlainPort();
    void transferCoordinates(const double* coord, const int coord_len);  
    void transferCoordinatesParallel(const double* coord, const int coord_len);
   
    void transferData(const double* data, const int data_len);  
    void transferDataParallel(const double* data, const int data_len);
   
};
#endif
