#ifndef FSI_FSIDUMMYBABSTRACTIMPLEMENTATION_H_
#define FSI_FSIDUMMYBABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "fsi/FSIComm.h"

#include "Component.h"
namespace fsi { 

     class FSIDummyBAbstractImplementation;
}



class fsi::FSIDummyBAbstractImplementation: public Component ,public fsi::FSIComm{
     protected:
          
     public:
       FSIDummyBAbstractImplementation();
       virtual ~FSIDummyBAbstractImplementation();
		void transferDataParallel(const double* data, const int data_len);
		void transferCoordinatesParallel(const double* coord, const int coord_len);
};     


#endif
