#ifndef FSI_FSIDATA_H_
#define FSI_FSIDATA_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace fsi { 

     class FSIData;
}

class fsi::FSIData {
  public:
    virtual ~FSIData(){}
     virtual void dataAck(int& ack)=0;
     virtual void dataAckParallel(int& ack)=0;
     virtual void transferData(const int* coordId, const int coordId_len,const double* data, const int data_len)=0;
     virtual void transferDataParallel(const int* coordId, const int coordId_len,const double* data, const int data_len)=0;


};

#endif
