#ifndef FSI_FSIDUMMYBABSTRACTIMPLEMENTATION_H_
#define FSI_FSIDUMMYBABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "fsi/FSIComm.h"

#include "Component.h"
namespace fsi { 

     class FSIDummyBAbstractImplementation;
}



class fsi::FSIDummyBAbstractImplementation: public Component ,public fsi::FSIComm{
     protected:
          
     public:
       FSIDummyBAbstractImplementation();
       virtual ~FSIDummyBAbstractImplementation();
		void endDataTransferParallel(int& ack);
		void startDataTransferParallel();
		void transferCoordinatesParallel(const int* coordId, const int coordId_len,const int* offsets, const int offsets_len,const std::string* hosts, const int hosts_len);
};     


#endif
