#ifndef FSI_FSITEST2NATIVE2JAVAPLAINPORT_H_
#define FSI_FSITEST2NATIVE2JAVAPLAINPORT_H_ 

#include "fsi/FSITest.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_fsi_FSITestNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_fsi_FSITestNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace fsi { 

     class FSITestNative2JavaPlainPort;
}

class fsi::FSITestNative2JavaPlainPort: public fsi::FSITest{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    FSITestNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~FSITestNative2JavaPlainPort();
    void test();  
    void testParallel();
   
};
#endif
