#ifndef FSI_FSITEST_H_
#define FSI_FSITEST_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace fsi { 

     class FSITest;
}

class fsi::FSITest {
  public:
    virtual ~FSITest(){}
     virtual void test()=0;
     virtual void testParallel()=0;


};

#endif
