.TH binprecice 1  "January 18, 2019" "USER COMMANDS"

.SH NAME
binprecice \- dumps the xml reference used for the configuration of libprecice

.SH SYNOPSIS
.B binprecice xml
|
.B dtd

.SH OPTIONS
.TP
.B xml
Prints the XML reference
.TP
.B dtd
Prints the DTD for the XML config

.SH RETURN VALUES
binprecice returns a zero exist status if it succeeds.
Non zero is returned in case of failure.

.SH AUTHOR
Frédéric Simonis (simonis (at) in.tum.de)

.SH SEE ALSO
testprecice(1)
.PP
www.precice.org \- the website of the project
