.TH precice-tools 1

.SH NAME
precice-tools \- command line utility for preCICE

.SH SYNOPSIS
.B precice-tools xml
|
.B dtd
|
.B md
|
[\fB version \fR|\fB --version \fR]
|
.B check \fIfile\fR [\fIparticipant\fR [\fIsize\fR]]

.SH OPTIONS

.TP
.B xml
Prints the configuration reference as XML with inlined help to the standard output.

.TP
.B dtd
Prints the DTD file to the standard output, which may be used to check XML configuration files.

.TP
.B md
Prints the configuration reference as markdown to the standard output.

.TP
.B version \fR|\fB --version \fR
Prints the preCICE version string ( \fIprecice::getVersionInformation()\fR ) to the standard output.

.TP
.B check \fIfile\fR [\fIparticipant\fR [\fIsize\fR]]
Checks given preCICE configuration \fIfile\fR and prints any errors. Pass the name of a \fIparticipant\fR to fully check its configuration. The optional \fIsize\fR indicates how many ranks run in parallel, which checks custom \fI<intra-comm: ... />\fR tags.

.SH EXIT STATUS
precice-tools returns a zero exit status if it succeeds to run the provided command.
Non zero is returned in case of failure.

.SH SEE ALSO
.BR precice-version (1),
.BR precice-config-validate (1),
.BR precice-config-doc (1)

.PP
precice.org \- the website of the project
