.TH precice-version 1

.SH NAME
precice-version \- command line utility to show the version of preCICE

.SH SYNOPSIS
.B precice-version

.SH EXIT STATUS
precice-version returns a zero exit status if it succeeds to run the provided command.
Non zero is returned in case of failure.

.SH SEE ALSO
.BR precice-config-validate (1),
.BR precice-config-doc (1)
.PP
precice.org \- the website of the project
