#ifndef _TARCH_PARALLEL_MESSAGES_JOBREQUESTMESSAGE_H
#define _TARCH_PARALLEL_MESSAGES_JOBREQUESTMESSAGE_H

#include "tarch/compiler/CompilerSpecificSettings.h"
#include "peano/utils/PeanoOptimisations.h"
#ifdef Parallel
	#include "tarch/parallel/Node.h"
#endif
#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <complex>
#include <string>
#include <iostream>

namespace tarch {
   namespace parallel {
      namespace messages {
         class JobRequestMessage;
         class JobRequestMessagePacked;
      }
   }
}

/**
 * @author This class is generated by DaStGen
 * 		   DataStructureGenerator (DaStGen)
 * 		   2007-2009 Wolfgang Eckhardt
 * 		   2012      Tobias Weinzierl
 *
 * 		   build date: 17-10-2012 11:04
 *
 * @date   17/10/2012 11:05
 */
class tarch::parallel::messages::JobRequestMessage { 
   
   public:
      
      typedef tarch::parallel::messages::JobRequestMessagePacked Packed;
      
      struct PersistentRecords {
         bool _dummy;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const bool& dummy);
         
         /**
          * Generated
          */
          bool getDummy() const ;
         
         /**
          * Generated
          */
          void setDummy(const bool& dummy) ;
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      JobRequestMessage();
      
      /**
       * Generated
       */
      JobRequestMessage(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      JobRequestMessage(const bool& dummy);
      
      /**
       * Generated
       */
      virtual ~JobRequestMessage();
      
      /**
       * Generated
       */
       bool getDummy() const ;
      
      /**
       * Generated
       */
       void setDummy(const bool& dummy) ;
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      JobRequestMessagePacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          * There are two variants: Datatype identifies only those attributes marked with
          * parallelise. FullDatatype instead identifies the whole record with all fields.
          */
         static MPI_Datatype Datatype;
         static MPI_Datatype FullDatatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
         
         void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
         
         static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class is generated by DaStGen
    * 		   DataStructureGenerator (DaStGen)
    * 		   2007-2009 Wolfgang Eckhardt
    * 		   2012      Tobias Weinzierl
    *
    * 		   build date: 17-10-2012 11:04
    *
    * @date   17/10/2012 11:05
    */
   class tarch::parallel::messages::JobRequestMessagePacked { 
      
      public:
         
         struct PersistentRecords {
            
            /** mapping of records:
            || Member 	|| startbit 	|| length
             |  dummy	| startbit 0	| #bits 1
             */
            short int _packedRecords0;
            
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const bool& dummy);
            
            /**
             * Generated
             */
             bool getDummy() const ;
            
            /**
             * Generated
             */
             void setDummy(const bool& dummy) ;
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         JobRequestMessagePacked();
         
         /**
          * Generated
          */
         JobRequestMessagePacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         JobRequestMessagePacked(const bool& dummy);
         
         /**
          * Generated
          */
         virtual ~JobRequestMessagePacked();
         
         /**
          * Generated
          */
          bool getDummy() const ;
         
         /**
          * Generated
          */
          void setDummy(const bool& dummy) ;
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         JobRequestMessage convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             * There are two variants: Datatype identifies only those attributes marked with
             * parallelise. FullDatatype instead identifies the whole record with all fields.
             */
            static MPI_Datatype Datatype;
            static MPI_Datatype FullDatatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            void receive(int source, int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            static bool isMessageInQueue(int tag, bool exchangeOnlyAttributesMarkedWithParallelise);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
