CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/__PATH_FULL_QUALIFIED_NAME__AbstractImplementation.cpp src/__PATH_FULL_QUALIFIED_NAME__Implementation.cpp components/java/__PATH_FULL_QUALIFIED_NAME__JNIProxy.cpp 
OBJS=$(subst .cpp,.o,$(SRCS))

all: libFSIDummyB.so

libFSIDummyB.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libFSIDummyB.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libFSIDummyB.so
