#ifndef PRECICE_AIMPLEMENTATION_H_
#define PRECICE_AIMPLEMENTATION_H_

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov
//

#include "precice/AAbstractImplementation.h"

#include <string>
#include <vector>

namespace precice {
class AImplementation;
}

class precice::AImplementation : public precice::AAbstractImplementation {
public:
  AImplementation();

  ~AImplementation();

  void
  main();

  void
  initializeAddresses(std::string const* addresses,
                      int const          addresses_size);

  void
  initializeVertexes(int const* vertexes,
                     int const  vertexes_size);

  void
  send(std::string const address, double const* data, int const data_size);

private:
  std::vector<std::string> _addresses;
  std::vector<std::string> _b_addresses;

  pthread_mutex_t _mutex;
};

#endif
