#ifndef PRECICE_AIMPLEMENTATION_H_
#define PRECICE_AIMPLEMENTATION_H_

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov
//

#include "precice/AAbstractImplementation.h"

#include <string>
#include <vector>

namespace precice {
class AImplementation;
}

class precice::AImplementation : public precice::AAbstractImplementation {
public:
  AImplementation();

  ~AImplementation();

  void
  main();

  void
  task();

  bool
  initialize();

  void
  acknowledge(int identifier, int& tag);

  void
  initialize(std::string const* addresses,
             int                addresses_size,
             int const*         vertexes,
             int                vertexes_size);

  void
  send();

  // void
  // send(std::string const address, double const* data, int const data_size);

  void
  send(double data, int index, int b_rank);

private:
  std::vector<std::string> _addresses;
  std::vector<std::string> _b_addresses;

  std::vector<int> _vertexes;
  std::vector<int> _b_vertexes;

  int const _rank;
  int       _counter;

  std::vector<double> _data;

  pthread_mutex_t _task_mutex;

  pthread_mutex_t _initialize_mutex;
  pthread_cond_t  _initialize_cond;
  bool            _initialized;
};

#endif
