//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov
//
package precice;

public class AJavaImplementation extends ABasisJavaImplementation {
  public AJavaImplementation(String identifier) throws
  de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }

  public boolean
  isValid() {
    return true;
  }

  public boolean
  hasGUI() {
    return true;
  }

  public void
  openGUI() {
    mainParallel();
  }

  public void
  closeGUI() {}

  public void
  destroy() {
    super.destroy();
  }
}
