//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package precice;


public class BBasisJavaImplementation extends precice.BAbstractJavaImplementation {
  public BBasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

