#ifndef PRECICE_BIMPLEMENTATION_H_
#define PRECICE_BIMPLEMENTATION_H_

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov
//

#include "precice/BAbstractImplementation.h"

#include <string>
#include <vector>

namespace precice {
class BImplementation;
}

class precice::BImplementation : public precice::BAbstractImplementation {
public:
  BImplementation();

  ~BImplementation();

  void
  main();

  void
  initializeAddresses(std::string const* addresses,
                      int const          addresses_size);

  void
  initializeVertexes(int const* vertexes,
                     int const  vertexes_size);

  void
  setData(double const* data, int const data_size);

private:
  std::vector<std::string> _addresses;
  std::vector<std::string> _a_addresses;

  pthread_mutex_t _mutex;
};

#endif
