#ifndef COMPONENT_H_
#define COMPONENT_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//


class Component{
  public:
    virtual ~Component(){}
    


};

#endif
