"""
Parses the format that is generated by the EventTimings framework. Sample input:
"""

import pandas


def getDataFrame(file):
    df = pandas.read_csv(file, index_col = [0, 1, 2], comment = "#", parse_dates = [0])
    return df.sort_index()


def latestRun(df):
    return df.loc[df.index.max()[0]]
