name: Run pre-commit checks
# Runs the pre-commit checks for all files changed.
#
# While a pre-commit job is included as a dependency of build-and-test.yml,
# that workflow is only triggered for a subset of files,
# excluding, e.g., documentation and scripts under .github/.
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  pre-commit:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
         python-version: '3.x'
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1