//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package fsi;


public class FSIDummyABasisJavaImplementation extends fsi.FSIDummyAAbstractJavaImplementation {
  public FSIDummyABasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

