#ifndef FSI_FSIDUMMYAIMPLEMENTATION_H_
#define FSI_FSIDUMMYAIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include <mpi.h>
#include "fsi/FSIDummyAAbstractImplementation.h"
#include <string>
#include <hash_map>
namespace fsi { 

class FSIDummyAImplementation;
}

class fsi::FSIDummyAImplementation : public fsi::FSIDummyAAbstractImplementation{
private:
	pthread_mutex_t _mutex;
	__gnu_cxx::hash_map<int,int> _global2LocalCoordMapping;
	std::vector<std::string> _mids;
	std::vector<int> _globalCoordIds;
	std::vector<int> _globaOffsets;
	double* _data;
	int* _localCoordIds;
	int _numberOfPoints;

	//void gatherMids();
	//void gatherDomainDescriptions();
public:
	static FSIDummyAImplementation* singleton;
	FSIDummyAImplementation();
	~FSIDummyAImplementation();
	void gatherMids();
	void gatherDomainDescriptions();

	void setCoordIds(int* coordIds,const int numberOfPoints);
	void setData(double* data);
	void transferData(
			const int* coordIds, const int coordIds_len,
			const double* data, const int data_len);
	void dataAck(int& ack);
	void startDataTransfer();
	void endDataTransfer(int& ack);
	void transferGlobalIds();
	void receiveAllData();
};     


#endif
