#ifndef FSI_FSIDUMMYBIMPLEMENTATION_H_
#define FSI_FSIDUMMYBIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "fsi/FSIDummyBAbstractImplementation.h"
#include <string>
namespace fsi { 

     class FSIDummyBImplementation;
}

class fsi::FSIDummyBImplementation : public fsi::FSIDummyBAbstractImplementation{
     public:
          FSIDummyBImplementation();
          ~FSIDummyBImplementation();
          void transferCoordinates(const double* coord, const int coord_len);
          void transferData(const double* data, const int data_len);
};     


#endif
